spring:
    datasource:
        password: brtax
        username: brtax
        url: jdbc:postgresql://localhost/brtax
    flyway:
        baseline-on-migrate: true
        clean-on-validation-error: true
        clean-disabled: false